const menuItems = [
    { id: 1, name: "Bruschetta", category: "Starter", price: "8.50", description: "A delicious appetizer to start your meal." },
    { id: 2, name: "Grilled Salmon", category: "Main", price: "18.99", description: "A hearty and satisfying main course." },
    { id: 3, name: "Chocolate Cake", category: "Dessert", price: "6.75", description: "A sweet treat to finish your meal." },
    { id: 4, name: "Garlic Bread", category: "Starter", price: "5.99", description: "Toasty and flavorful bread with garlic." },
    { id: 5, name: "Spaghetti Carbonara", category: "Main", price: "16.50", description: "Classic pasta with creamy sauce." },
    { id: 6, name: "Apple Pie", category: "Dessert", price: "7.25", description: "A traditional dessert with a flaky crust." },
    { id: 7, name: "Caprese Salad", category: "Starter", price: "9.75", description: "Fresh tomatoes, mozzarella, and basil." },
    { id: 8, name: "Chicken Parmesan", category: "Main", price: "17.99", description: "Crispy chicken with marinara sauce." },
    { id: 9, name: "Tiramisu", category: "Dessert", price: "7.99", description: "A classic Italian coffee-flavored dessert." },
    { id: 10, name: "Spring Rolls", category: "Starter", price: "8.25", description: "Crispy rolls with a savory filling." },
    { id: 11, name: "Beef Stroganoff", category: "Main", price: "19.50", description: "Tender beef in a creamy sauce." },
    { id: 12, name: "Cheesecake", category: "Dessert", price: "7.50", description: "Rich and creamy dessert with a crust." },
    { id: 13, name: "Shrimp Cocktail", category: "Starter", price: "10.50", description: "Fresh shrimp served with tangy sauce." },
    { id: 14, name: "Vegetarian Pizza", category: "Main", price: "15.75", description: "Loaded with fresh vegetables." },
    { id: 15, name: "Ice Cream Sundae", category: "Dessert", price: "5.99", description: "Creamy ice cream with toppings." },
    { id: 16, name: "Stuffed Mushrooms", category: "Starter", price: "9.25", description: "Mushrooms filled with savory stuffing." },
    { id: 17, name: "Roast Chicken", category: "Main", price: "17.50", description: "Juicy chicken roasted to perfection." },
    { id: 18, name: "Brownie", category: "Dessert", price: "6.25", description: "Fudgy and rich chocolate treat." },
    { id: 19, name: "Calamari", category: "Starter", price: "11.75", description: "Crispy fried calamari with dip." },
    { id: 20, name: "Pasta Primavera", category: "Main", price: "14.99", description: "Pasta tossed with fresh vegetables." },
    { id: 21, name: "Panna Cotta", category: "Dessert", price: "6.99", description: "Smooth and creamy Italian dessert." },
    { id: 22, name: "Tomato Soup", category: "Starter", price: "7.25", description: "Warm and comforting soup." },
    { id: 23, name: "Lamb Chops", category: "Main", price: "21.50", description: "Succulent lamb chops grilled to perfection." },
    { id: 24, name: "Fruit Tart", category: "Dessert", price: "7.75", description: "Flaky crust with fresh fruits." },
    { id: 25, name: "Crab Cakes", category: "Starter", price: "12.25", description: "Savory cakes with fresh crab meat." },
    { id: 26, name: "Seafood Paella", category: "Main", price: "22.50", description: "A Spanish dish with seafood and rice." },
    { id: 27, name: "Lemon Sorbet", category: "Dessert", price: "5.50", description: "Refreshing and tangy frozen treat." },
    { id: 28, name: "Mozzarella Sticks", category: "Starter", price: "8.75", description: "Cheesy and crispy snack." },
    { id: 29, name: "Vegetable Stir-fry", category: "Main", price: "13.99", description: "Colorful veggies with a savory sauce." },
    { id: 30, name: "Custard Pudding", category: "Dessert", price: "6.50", description: "Silky and sweet pudding." },
    { id: 31, name: "Charcuterie Board", category: "Starter", price: "14.99", description: "An assortment of meats and cheeses." },
    { id: 32, name: "Baked Ziti", category: "Main", price: "16.50", description: "Pasta baked with cheese and sauce." },
    { id: 33, name: "Profiteroles", category: "Dessert", price: "7.25", description: "Cream-filled pastries with chocolate." },
    { id: 34, name: "Avocado Toast", category: "Starter", price: "9.50", description: "Toasted bread with creamy avocado." },
    { id: 35, name: "Steak Frites", category: "Main", price: "23.50", description: "Juicy steak with crispy fries." },
    { id: 36, name: "Carrot Cake", category: "Dessert", price: "6.99", description: "Moist cake with a hint of spice." },
    { id: 37, name: "Hummus Platter", category: "Starter", price: "8.25", description: "Creamy hummus served with pita." },
    { id: 38, name: "Fish and Chips", category: "Main", price: "15.75", description: "Crispy fish with fries." },
    { id: 39, name: "Macarons", category: "Dessert", price: "8.25", description: "Colorful and delicate French cookies." },
    { id: 40, name: "Crispy Tofu", category: "Starter", price: "9.50", description: "Golden fried tofu with dipping sauce." },
    { id: 41, name: "Lasagna", category: "Main", price: "16.99", description: "Layered pasta with meat and cheese." },
    { id: 42, name: "Churros", category: "Dessert", price: "6.75", description: "Fried dough with cinnamon sugar." },
    { id: 43, name: "Chicken Wings", category: "Starter", price: "10.25", description: "Spicy and tangy chicken wings." },
    { id: 44, name: "Pork Belly", category: "Main", price: "18.50", description: "Tender and flavorful pork belly." },
    { id: 45, name: "Creme Brulee", category: "Dessert", price: "7.50", description: "Rich custard with caramelized sugar." },
    { id: 46, name: "Deviled Eggs", category: "Starter", price: "6.50", description: "Egg halves filled with seasoned yolks." },
    { id: 47, name: "Duck Confit", category: "Main", price: "20.99", description: "Slow-cooked duck with crispy skin." },
    { id: 48, name: "Eclairs", category: "Dessert", price: "7.25", description: "Pastry filled with cream and topped with chocolate." },
    { id: 49, name: "Meatballs", category: "Starter", price: "9.99", description: "Savory and tender meatballs." },
    { id: 50, name: "Ratatouille", category: "Main", price: "14.50", description: "A French vegetable medley." }
  ];
  
  export default menuItems;
  